### ISSUE TITLE
White Balance different on red channel?

### ISSUE THREAD

**Issue by BlueByLiquid** [lincomatic/Colorduino#5]
*it seems white balance is inversely set. For example if set white balance on the red channel to 0 red is very bright, if I set it to 63 it is very low. The blue and green channel work in the opposite way. This is particular noticeable if you run individual LEDs rather than an RGB led with them inside.

**Comment by lincomatic** [comment]
I have tested it, and the red channel behaves just like the rest of the channels. Maybe your red channel is hooked up wrong?
